"""Visualize tissue masks as RGB, mask, and overlay panels."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def _normalize01(img: np.ndarray) -> np.ndarray:
    img = img.astype(np.float32, copy=False)
    lo = np.percentile(img, 2.0)
    hi = np.percentile(img, 98.0)
    if hi <= lo:
        return np.zeros_like(img, dtype=np.float32)
    out = (img - lo) / (hi - lo)
    return np.clip(out, 0.0, 1.0)


def _cube_to_rgb(cube: np.ndarray) -> np.ndarray:
    """Map (H, W, C) cube to pseudo-RGB in [0, 1]."""
    if cube.ndim != 3:
        raise ValueError(f"Expected cube shape (H, W, C), got {cube.shape}")
    c = cube.shape[2]
    if c < 3:
        gray = _normalize01(cube.mean(axis=2))
        return np.stack([gray, gray, gray], axis=-1)

    ridx = int(round(0.75 * (c - 1)))
    gidx = int(round(0.50 * (c - 1)))
    bidx = int(round(0.25 * (c - 1)))
    rgb = np.stack([cube[:, :, ridx], cube[:, :, gidx], cube[:, :, bidx]], axis=-1)
    return _normalize01(rgb)


def _save_preview(cube_path: Path, mask_path: Path, out_path: Path, alpha: float) -> None:
    cube = np.load(cube_path, allow_pickle=False)
    mask = np.load(mask_path, allow_pickle=False)
    if mask.ndim != 2:
        raise ValueError(f"Expected 2D mask, got {mask.shape} at {mask_path}")

    rgb = _cube_to_rgb(cube)
    mask_bool = mask.astype(bool)

    overlay = rgb.copy()
    red = np.zeros_like(rgb)
    red[..., 0] = 1.0
    overlay[mask_bool] = (1.0 - alpha) * overlay[mask_bool] + alpha * red[mask_bool]

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(rgb)
    axes[0].set_title("Pseudo-RGB")
    axes[0].axis("off")

    axes[1].imshow(mask_bool, cmap="gray")
    axes[1].set_title("Tissue Mask")
    axes[1].axis("off")

    axes[2].imshow(overlay)
    axes[2].set_title("Overlay")
    axes[2].axis("off")

    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=140)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize tissue masks from mask_manifest.csv")
    parser.add_argument(
        "--mask-manifest",
        type=str,
        required=True,
        help="Path to mask_manifest.csv generated by build_masks_from_avg3.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="data/interim/masks/previews",
        help="Directory where PNG previews are saved.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=20,
        help="Maximum number of rows to visualize.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used when sampling rows.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.45,
        help="Overlay opacity for the red tissue mask [0, 1].",
    )
    parser.add_argument(
        "--sort-by-tissue",
        action="store_true",
        help="If set, visualize highest tissue_ratio samples first.",
    )
    args = parser.parse_args()

    manifest_path = Path(args.mask_manifest).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(manifest_path)
    required = {"patient_id", "roi_name", "cube_path", "mask_path", "tissue_ratio"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Manifest missing required columns: {sorted(missing)}")
    if df.empty:
        raise ValueError(f"Manifest has no rows: {manifest_path}")

    if args.sort_by_tissue:
        selected = df.sort_values("tissue_ratio", ascending=False).head(args.max_samples)
    else:
        n = min(args.max_samples, len(df))
        selected = df.sample(n=n, random_state=args.seed)

    saved = 0
    for _, row in selected.iterrows():
        patient_id = str(row["patient_id"])
        roi_name = str(row["roi_name"])
        tissue = float(row["tissue_ratio"])
        cube_path = Path(str(row["cube_path"]))
        mask_path = Path(str(row["mask_path"]))

        if not cube_path.exists() or not mask_path.exists():
            print(f"Skipping missing files for {patient_id}/{roi_name}")
            continue

        filename = f"{patient_id}__{roi_name}__t{tissue:.3f}.png"
        out_path = output_dir / filename
        _save_preview(cube_path=cube_path, mask_path=mask_path, out_path=out_path, alpha=args.alpha)
        saved += 1

    print(f"Saved previews: {saved}")
    print(f"Preview directory: {output_dir}")


if __name__ == "__main__":
    main()
