<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets/icon-256x256px.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Set OSPlatform type boolean -->
    <PropertyGroup>
        <IsMacOSTarget Condition="$(RuntimeIdentifier.StartsWith('osx'))">true</IsMacOSTarget>
        <IsMacOSTarget Condition="'$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOSPlatform('OSX'))">true</IsMacOSTarget>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>
    
    <!-- Exclude macOS resource-fork ghost files created on FAT/exFAT volumes -->
    <ItemGroup>
        <Compile Remove="**/._*.cs"/>
        <AvaloniaResource Remove="**/._*.axaml"/>
    </ItemGroup>

    <!-- Base ModelsPackages: copied to output on build -->
    <ItemGroup>
        <None Include="ModelPackages\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3"/>
        <PackageReference Include="PanAndZoom" Version="11.3.9.1"/>
        <PackageReference Include="QuestPDF" Version="2026.2.4" />
        <PackageReference Include="ScottPlot.Avalonia" Version="5.1.58" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.93.0" />
        <!-- <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1"/> -->
    </ItemGroup>

    <!-- If macOS: CPU and CoreML OnnxRuntime -->
    <ItemGroup Condition="'$(IsMacOSTarget)' == 'true'">
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    </ItemGroup>

    <!-- If Windows/Linux: CUDA and CPU OnnxRuntime -->
    <ItemGroup Condition="'$(IsMacOSTarget)' != 'true'">
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.20.1" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\ImageViewBackup.axaml.cs">
            <DependentUpon>ImageViewBackup.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ModelsView.axaml.cs">
            <DependentUpon>ModelsView.axaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ModelPackages\" />
    </ItemGroup>
</Project>
